name             'api-umbrella'
maintainer       'National Renewable Energy Laboratory'
maintainer_email 'nick.muerdter@nrel.gov'
license          'All rights reserved'
description      'Installs/Configures api-umbrella'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.2'

depends 'acl', '~> 0.1.0'
depends 'bundler', '~> 0.1.5'
depends 'elasticsearch', '~> 0.3.7'
depends 'envbuilder', '~> 0.2.0'
depends 'geoip', '~> 0.1.0'
depends 'git', '~> 2.8.4'
depends 'iptables', '~> 0.10.2'
depends 'java', '~> 1.17.4'
depends 'logrotate', '~> 1.4.0'
depends 'man', '~> 0.7.0'
depends 'mongodb', '~> 0.14.4'
depends 'nginx', '~> 2.0.1'
depends 'nodejs', '~> 1.3.0'
depends 'ntp', '~> 1.5.4'
depends 'pygments', '~> 0.0.2'
depends 'redis', '~> 0.1.8'
depends 'rbenv', '~> 0.7.3'
depends 'ruby_build', '~> 0.8.0'
depends 'rubygems', '~> 0.1.3'
depends 'selinux', '~> 0.6.2'
depends 'shasum', '~> 0.0.2'
depends 'sudo', '~> 2.2.3'
depends 'supervisor', '~> 0.4.11'
depends 'varnish', '~> 0.9.11'
depends 'xml', '~> 1.2.0'
